[package]
name = "wasm-module-template"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
name = "module"
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[dependencies]
"wasm-bindgen" = "0.2.103"